name: preprocessing-stack

services:
  notebook:
    build:
      context: .
      dockerfile: docker/Dockerfile.services
      target: notebook
    image: preprocessing:notebook
    container_name: preprocessing-notebook
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ~/Escritorio/Datasets:/workspace/Data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tmp/:/tmp/
    ports:
      - "8888:8888"
    environment:
      - PYTHONPATH=/workspace
    gpus: all


